UPDATE orders
SET id_evento = CASE
    WHEN MONTH(ORDER_DATE) = 11 AND DAY(ORDER_DATE) BETWEEN 24 AND 30 THEN 1 -- 'Black Friday'
    WHEN MONTH(ORDER_DATE) = 12 AND DAY(ORDER_DATE) = 2 THEN 2 -- 'Cyber Monday'
    WHEN MONTH(ORDER_DATE) = 12 AND DAY(ORDER_DATE) BETWEEN 18 AND 25 THEN 3 -- 'Navidad'
    ELSE NULL
END
WHERE id_evento IS NULL;
