UPDATE orders
SET id_evento = CASE
    WHEN MONTH(o.ORDER_DATE) = 12 AND DAY(o.ORDER_DATE) = 26 AND c.NATION_KEY = 23 THEN 4 -- 'Boxing Day'
    WHEN (MONTH(o.ORDER_DATE) = 1 AND DAY(o.ORDER_DATE) >= 10) OR (MONTH(o.ORDER_DATE) = 2 AND DAY(o.ORDER_DATE) <= 20) AND c.NATION_KEY = 6 THEN 5 -- 'Rebajas de invierno'
    WHEN MONTH(o.ORDER_DATE) = 7 AND DAY(o.ORDER_DATE) = 4 AND c.NATION_KEY = 24 THEN 6 -- 'Independence Day'
    ELSE NULL
END
FROM orders o
JOIN CUSTOMERS c ON o.CUSTOMER_KEY = c.CUSTOMER_KEY
WHERE o.id_evento IS NULL;
